### ISSUE TITLE
How to use garak to call a model deployed remotely using VLLM

### ISSUE THREAD

**Issue by xiaoqing928** [NVIDIA/garak#1134]
If I deploy the qwen32 model using vllm on server A, the model interface is http://ip:port/v1/chat/completions, Model name is qwen2.5-32b.
How to use garak to test the model on server B, How should I set model_type, model_name, and api_key?
I am looking forward to your answer very much，Thanks!!!

**Comment by JanetVictorious** [comment]
Since vLLM is OpenAI compatible you can use the `OpenAICompatible` generator for scanning a model served with vLLM. This is an example config:

```yaml
# config.yaml
---
plugins:
  generators:
    openai:
      OpenAICompatible:
        uri: http://ip:port/v1  # <-- Put your host where vLLM is served here
        temperature: 0.6
        top_p: 1.0
        suppressed_params:
          - n
          - frequency_penalty
          - presence_penalty
  model_name: qwen2.5-32b  # <-- Put your hosted model name here
  model_type: openai.OpenAICompatible
```
