### ISSUE TITLE
Calibration in v0.11.0 seems to have missed some name changes introduced in PR #1178 resulting in missing Z-scores

### ISSUE THREAD

**Issue by aishwaryap** [NVIDIA/garak#1239]
## Steps to reproduce

Sample config `v_0_11_release__DeepSeek-R1-Distill-Llama-8B__max_tokens4096__probe_grandma.Slurs.conf` run with `garak==v0.11.0`
```
system:
  parallel_attempts: 128
  lite: false

run:
  generations: 5

plugins:
  probe_spec: grandma.Slurs
  extended_detectors: false
  probes:
    encoding:
      payloads:
        - default
        - xss
        - slur_terms
  detectors:
    misleading:
      MustContradictNLI:
        hf_args:
          device: cpu
      MustRefuteClaimModel:
        hf_args:
          device: cpu
  model_type: openai.OpenAICompatible
  model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  generators:
    openai:
      OpenAICompatible:
        uri: http://localhost:8000/v1
        api_key: "EMPTY"
        model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
        max_tokens: 4096
      temperature: 0.6
      top_p: 0.95
      use_chat: True
      skip_seq_start:
      skip_seq_end: </think>
```

Env details: 
```
conda init
conda create --prefix <my_env_path> python==3.12
conda activate <my_env_path>
pip install garak==0.11.0 vllm
```

Run Details:
```
vllm serve deepseek-ai/DeepSeek-R1-Distill-Llama-8B --tensor_parallel_size 8 &
sleep 600 # Waiting for VLLM to start up
XDG_DATA_HOME=<my_report_path>  garak --config v_0_11_release__DeepSeek-R1-Distill-Llama-8B__max_tokens4096__probe_grandma.Slurs.conf
```

Examine generated report HTML.
Report HTML mentions that for probe `grandma.Slurs ` with detector `unsafe_content.SlursReclaimedSlurs`, 
```
relative score (Z): unavailable, calibration not present for this probe:detector combination
```
However, previous versions of garak included calibration for probe `grandma.Slurs` with detector `specialwords.SlursReclaimedSlurs` which has been renamed in [PR 1178](https://github.com/NVIDIA/garak/pull/1178)

## Were you following a specific guide/tutorial or reading documentation?

N/A

## Expected behavior

Expected calibration to be available.

## Current behavior

No Z-scores provided

### garak version

0.11.0

## Additional Information

1. Linux
2. 3.12
3. Install method: pypi
4. Logs from execution run `report.html` / `report.jsonl` / `hitlog.jsonl` and if possible `garak.log`
